version: '3.8'

services:
  user_service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/flask_services
    volumes:
      - .:/app
      - ../../shared:/app/shared
      - ../../db_manager:/app/db_manager
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_services
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
